# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomebrewToto < Formula
  desc ""
  homepage "https://github.com/vickyonit/homebrew-toto"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_darwin_amd64.tar.gz"
      sha256 "cb459f3f4049d5b27e17dee67d1afd0d10b11dc2640413d8ce52df35dc490f41"

      def install
        bin.install "toto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_darwin_arm64.tar.gz"
      sha256 "21ff6d830fb556e7dd417dfdb9cb2e6697a864bf1e3d399593ea16d261b1b608"

      def install
        bin.install "toto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_linux_arm64.tar.gz"
      sha256 "ea3c28158455ea5807be76dc1d7fcbc6c4a2af04ba00ad1ac5b6938c59f5a5cc"

      def install
        bin.install "toto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_linux_amd64.tar.gz"
      sha256 "94547726f9a891f7b117ddad46ca978854724dd82981ecb9a623de8531a6c31c"

      def install
        bin.install "toto"
      end
    end
  end
end
