# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toto < Formula
  desc ""
  homepage "https://github.com/vickyonit/homebrew-toto"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_darwin_amd64.tar.gz"
      sha256 "780ff00ec38a5e1286ed6d031b4e681faf041e3829d6c9810bb319090fb35357"

      def install
        bin.install "toto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_darwin_arm64.tar.gz"
      sha256 "7f8cdff5729016f6477457ffcf0ccea6b7e922573ea7b7a6e88b41a9a4b40636"

      def install
        bin.install "toto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_linux_arm64.tar.gz"
      sha256 "179775a7cb1c9eac32c5a290677f6326cf96d551bf0b0ccd2bf459555f7105d8"

      def install
        bin.install "toto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vickyonit/toto/releases/download/v0.0.2/toto_0.0.2_linux_amd64.tar.gz"
      sha256 "3df844061600117ca29c16675bc3f268aec41a7e306c0a7db2019cc66c7e39b2"

      def install
        bin.install "toto"
      end
    end
  end
end
